version: "3.8"

networks:
  service_marketplace:
    driver: bridge

volumes:
  postgres_data:
  postgres_test_data:

services:

  db:
    image: postgres:17
    container_name: service_marketplace_db
    env_file:
      - .env.development
    restart: always

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - service_marketplace

  db_test:
    image: postgres:17
    container_name: service_marketplace_db_test
    env_file:
      - .env.test
    restart: always

    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

    networks:
      - service_marketplace

  
  service_marketplace: 
    build: .
    depends_on:
      - db
    env_file:
      - .env.docker
    ports: 
      - "${PORT:-5520}:${PORT:-5520}"
