version: "3.8"

networks:
  service_marketplace:
    driver: bridge

volumes:
  postgres_data:
  postgres_test_data:

services:

  postgres:
    image: postgres:17
    container_name: service_marketplace_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: service_marketplace_database

    restart: always

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - service_marketplace


  postgres_test:
    image: postgres:17
    container_name: service_marketplace_db_test

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: service_marketplace_database_test

    restart: always

    ports:
      - "5432:5432"

    volumes:
      - postgres_test_data:/var/lib/postgresql/data

    networks:
      - service_marketplace
